#
# Copyright (c) 2020, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

commands:
  install_sdk:
    description: "Install the DAML SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          command: |
            cd ${HOME}
            wget https://github.com/digital-asset/daml/releases/download/v<< parameters.version >>/daml-sdk-<< parameters.version >>-linux.tar.gz
            tar -zxvf daml-sdk-<< parameters.version >>-linux.tar.gz
            cd sdk-<< parameters.version >>
            ./install.sh
            cd ${HOME}
            rm -rf sdk-<< parameters.version >>


jobs:
  build:
    docker:
     - image: circleci/python:3-node

    steps:
      - checkout
      - restore_cache:
          keys:
            - daml-{{ checksum "daml.yaml" }}
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends openjdk-11-jdk
      - install_sdk:
          version: "1.4.0"
      - save_cache:
          paths:
            - ~/.daml
          key: daml-{{ checksum "daml.yaml" }}
      - run:
          command: |
            pip install yq
            sudo pip install poetry
      - run:
          command: |
            export PATH=${HOME}/.daml/bin:${PATH}
            daml build
            daml test
            make clean
            make package
