export const classes = {
  container: 'container',
  logotypeContainer: 'logotypeContainer',
  formContainer: 'formContainer',
  form: 'form',
  errorMessage: 'errorMessage',
  damlHubLoginButton: 'damlHubLoginButton',
  textFieldUnderline: 'textFieldUnderline',
  formButtons: 'formButtons',
  loginLoader: 'loginLoader',
  textField: 'textField',
  appBar: 'appBar',
  logotype: 'logotype',
  toolbar: 'toolbar',
  grow: 'grow',
  headerIcon: 'headerIcon',
  headerMenuButton: 'headerMenuButton',
  newGameButton: 'newGameButton',
  tableRow: 'tableRow',
  tableCell: 'tableCell',
  paperRoot: 'paperRoot',
  textRow: 'textRow',
  safetyText: 'safetyText',
  errorCode: 'errorCode',
  backButton: 'backButton',
};
